markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "Rakefile"]
title : NOW

baseurl: /news-docs
date: 2015
author: Ontotext
ASSET_PATH : assets/boddhi

collections:
  v1_0_0-docs:
    output: false
  v1_2_0-docs:
    output: true
  v1_3_0-docs:
    output: true
