markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "Rakefile"]
title : NOW

baseurl: /now-docs
date: 2015
author: Ontotext
ASSET_PATH : assets/boddhi

collections:
  v1_0_0-docs:
    output: true
